; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328
framework = arduino
board_upload.protocol = arduino
board_upload.speed = 115200
lib_deps =
    NicoHood/PinChangeInterrupt @ ^1.2.9
